server:
  port: 9500

logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: service-catalogo
              uri: ${CATALOGO_URI:http://localhost:8080}
              predicates:
                - Path=/movies/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-socios
              uri: ${SOCIOS_URI:http://localhost:8080}
              predicates:
                - Path=/api/socios/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-users
              uri: ${USERS_URI:http://localhost:8080}
              predicates:
                - Path=/api/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-notificaciones
              uri: ${NOTIFICACIONES_URI:http://localhost:8080}
              predicates:
                - Path=/api/notifications/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: agent-service
              uri: ${AGENT_URI:http://localhost:8085}
              predicates:
                - Path=/api/agent/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
